### ISSUE TITLE
Regex doesn't match module source

### ISSUE THREAD

**Issue by robinbowes** [hayorov/terraform-init-booster#1]
Hi,

I've found that the regex you're using to extract the module name and tag does not match the URI we're using in our module source.

We're using: `git@github.com:github_user/terraform-aws-module_name.git?ref=2.0.0`

This re: matches the URI we're using:

```
MODULE_NAME_PATTERN = r".+/(.+)\.git\?ref=(.+)"
```

**Comment by hayorov** [comment]
Many thanks for the feedback @robinbowes
